import { DownloadModel, DownloadStatus, DownloadSource, Platform } from '../models/download.model';
import { Codecs, Types, VideoFormats, VideoQuality } from '../models/subscription.model';

export const DownloadRecordMock: DownloadModel = {
  id: 1,
  watcherId: null,
  channelId: 'ChannelId',
  channelName: 'Sample Channel',
  videoId: 'abc123',
  title: 'Sample Title',
  url: 'https://example.com/video/abc123',
  status: DownloadStatus.QUEUED,
  source: DownloadSource.MANUAL,
  platform: Platform.YOUTUBE,
  type: Types.VIDEO,
  format: VideoFormats.MP4,
  codec: Codecs.H264,
  quality: VideoQuality.BEST,
  folder: null,
  prefix: '',
  ytdlpArgs: '',
  clipStart: null,
  clipEnd: null,
  removeSponsor: false,
  splitChapters: false,
  playlistId: null,
  playlistTitle: null,
  playlistIndex: null,
  duration: 1200,
  progress: 0,
  speed: null,
  eta: null,
  totalBytes: 10240000,
  filePath: '/downloads/Sample Title.mp4',
  avatarPath: null,
  thumbnailPath: null,
  authorUrl: 'https://youtube.com/channel/ChannelId',
  error: null,
  createdAt: '2024-06-01T12:00:00Z',
  startedAt: null,
  finishedAt: null,
};
