// Propagates the version from the root package.json - the single source of
// truth - to everything else that carries it:
//   - backend/package.json and frontend/package.json "version"
//   - backend/package-lock.json (the package's own version fields)
//   - the Dockerfile's org.opencontainers.image.version label
//   - version.json: top-level version and releaseDate, plus an empty changelog
//     entry for a version that has none yet
//   - frontend/src/app/shared/constants/version.const.ts (the header chip)
// Run by the root `dev` and `build` scripts, and by scripts/release.sh after a
// bump, so none of them can drift from the root manifest.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

if (!/^\d+\.\d+\.\d+$/.test(version)) {
  console.error(`error: root package.json version "${version}" is not x.y.z`);
  process.exit(1);
}

// Skip the write when nothing changed: an unconditional write would churn the
// file's mtime and make the dev server rebuild on every start.
function update(relPath, transform) {
  const file = join(root, relPath);
  const before = existsSync(file) ? readFileSync(file, 'utf8') : null;
  const after = transform(before);
  if (after !== before) {
    writeFileSync(file, after);
    console.log(`${relPath} -> ${version}`);
  }
}

// Replace a pattern that must be present; a silent no-op would hide a renamed
// field or label until the next release ships with the old version.
function replaceRequired(relPath, pattern, replacement) {
  update(relPath, (s) => {
    if (s === null || !pattern.test(s)) {
      console.error(`error: no version found in ${relPath}`);
      process.exit(1);
    }
    return s.replace(pattern, replacement);
  });
}

// Regex rather than JSON.parse/stringify keeps each manifest's formatting and
// key order untouched. Only the first "version" key is the package's own.
for (const pkg of ['backend/package.json', 'frontend/package.json']) {
  replaceRequired(pkg, /("version":\s*")[^"]*(")/, `$1${version}$2`);
}

replaceRequired('Dockerfile', /(LABEL org\.opencontainers\.image\.version=")[^"]*(")/, `$1${version}$2`);

// Parse, edit, re-serialize. Both files below are plain 2-space JSON, so this
// round-trips byte for byte; the trailing newline is kept as found.
function updateJson(relPath, mutate) {
  update(relPath, (s) => {
    if (s === null) return s;
    const data = JSON.parse(s);
    mutate(data);
    return JSON.stringify(data, null, 2) + (s.endsWith('\n') ? '\n' : '');
  });
}

// version.json feeds the in-app changelog. The notes are written by hand, but a
// new version gets its entry scaffolded here, dated today. An existing entry is
// never touched, so re-running on a later day does not move its date.
updateJson('version.json', (data) => {
  data.changelog ??= [];
  let entry = data.changelog.find((e) => e.version === version);
  if (!entry) {
    const now = new Date();
    const today = [now.getFullYear(), now.getMonth() + 1, now.getDate()]
      .map((n) => String(n).padStart(2, '0'))
      .join('-');
    entry = {
      version,
      releaseDate: today,
      changelog: { bugfixes: [], features: [], improvements: [], other: [] },
    };
    data.changelog.unshift(entry);
  }
  data.version = version;
  data.releaseDate = entry.releaseDate;
});

// npm records the package's own version twice in its lockfile.
updateJson('backend/package-lock.json', (lock) => {
  lock.version = version;
  if (lock.packages?.['']) lock.packages[''].version = version;
});

update(
  'frontend/src/app/shared/constants/version.const.ts',
  () => `// Generated by scripts/generate-version.mjs - do not edit.
// Source of truth: package.json "version" (repo root).
export const APP_VERSION = '${version}';
`,
);
